"""Relacionamentos

Revision ID: 016edb5d511f
Revises: 567772495e6b
Create Date: 2022-05-23 12:35:58.583932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016edb5d511f'
down_revision = '567772495e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacionamento', sa.Column('id_solides', sa.String(), nullable=False))
    op.add_column('relacionamento', sa.Column('id_ad', sa.String(), nullable=True))
    op.add_column('relacionamento', sa.Column('id_avaya', sa.String(), nullable=True))
    op.drop_constraint('relacionamento_unidade_fkey', 'relacionamento', type_='foreignkey')
    op.drop_constraint('relacionamento_titular_fkey', 'relacionamento', type_='foreignkey')
    op.drop_constraint('relacionamento_ccomiss_fkey', 'relacionamento', type_='foreignkey')
    op.create_foreign_key(None, 'relacionamento', 'cgp_unidade', ['id_ad'], ['sigla'], ondelete='SET NULL')
    op.create_foreign_key(None, 'relacionamento', 'cgp_colaborador', ['id_avaya'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'relacionamento', 'cgp_ccomiss', ['id_solides'], ['codigo'], ondelete='CASCADE')
    op.drop_column('relacionamento', 'unidade')
    op.drop_column('relacionamento', 'ccomiss')
    op.drop_column('relacionamento', 'titular')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacionamento', sa.Column('titular', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('relacionamento', sa.Column('ccomiss', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('relacionamento', sa.Column('unidade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'relacionamento', type_='foreignkey')
    op.drop_constraint(None, 'relacionamento', type_='foreignkey')
    op.drop_constraint(None, 'relacionamento', type_='foreignkey')
    op.create_foreign_key('relacionamento_ccomiss_fkey', 'relacionamento', 'cgp_ccomiss', ['ccomiss'], ['codigo'], ondelete='CASCADE')
    op.create_foreign_key('relacionamento_titular_fkey', 'relacionamento', 'cgp_colaborador', ['titular'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key('relacionamento_unidade_fkey', 'relacionamento', 'cgp_unidade', ['unidade'], ['sigla'], ondelete='SET NULL')
    op.drop_column('relacionamento', 'id_avaya')
    op.drop_column('relacionamento', 'id_ad')
    op.drop_column('relacionamento', 'id_solides')
    # ### end Alembic commands ###
