"""empty message

Revision ID: 20f6d2fcdb5c
Revises: 8592e33105a2
Create Date: 2022-04-14 09:39:58.925768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20f6d2fcdb5c'
down_revision = '8592e33105a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('django_content_type')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index('oeb_satelite_base_07a404b9', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_base_07a404b9_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_entidade_a25587bd', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_entidade_a25587bd_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_funcgen_b8d6b7a6', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_funcgen_b8d6b7a6_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_nssdc_3c8b1650_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_orbita_d15b2592', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_orbita_d15b2592_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_status_528c4e00', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_status_528c4e00_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_vcge_a741bfd4', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_vcge_a741bfd4_like', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_veiculo_10f6c700', table_name='oeb_satelite')
    op.drop_index('oeb_satelite_veiculo_10f6c700_like', table_name='oeb_satelite')
    op.drop_table('oeb_satelite')
    op.drop_index('teste_distribccomiss_ccomiss_fcb54ec6', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_ccomiss_fcb54ec6_like', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_codigo_59e1c1dc_like', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_substituto_110b6333', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_substituto_110b6333_like', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_titular_4a41cc55', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_titular_4a41cc55_like', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_unidade_2a16a533', table_name='teste_distribccomiss')
    op.drop_index('teste_distribccomiss_unidade_2a16a533_like', table_name='teste_distribccomiss')
    op.drop_table('teste_distribccomiss')
    op.drop_index('oeb_entidade_codigo_7595804c_like', table_name='oeb_entidade')
    op.drop_table('oeb_entidade')
    op.drop_index('oeb_base_codigo_b1ebede0_like', table_name='oeb_base')
    op.drop_table('oeb_base')
    op.drop_index('teste_cefetivo_codigo_c691b85c_like', table_name='teste_cefetivo')
    op.drop_table('teste_cefetivo')
    op.drop_index('oeb_satpropri_codigo_10cd50e3_like', table_name='oeb_satpropri')
    op.drop_index('oeb_satpropri_entidade_2c531a8e', table_name='oeb_satpropri')
    op.drop_index('oeb_satpropri_entidade_2c531a8e_like', table_name='oeb_satpropri')
    op.drop_index('oeb_satpropri_satelite_9ac3b440', table_name='oeb_satpropri')
    op.drop_index('oeb_satpropri_satelite_9ac3b440_like', table_name='oeb_satpropri')
    op.drop_table('oeb_satpropri')
    op.drop_index('oeb_veiculo_codigo_d02fbc65_like', table_name='oeb_veiculo')
    op.drop_table('oeb_veiculo')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('oeb_status_codigo_c473e20b_like', table_name='oeb_status')
    op.drop_table('oeb_status')
    op.drop_index('teste_estcivil_codigo_b590c4c6_like', table_name='teste_estcivil')
    op.drop_table('teste_estcivil')
    op.drop_index('oeb_satfab_codigo_c16b5828_like', table_name='oeb_satfab')
    op.drop_index('oeb_satfab_entidade_3a159de4', table_name='oeb_satfab')
    op.drop_index('oeb_satfab_entidade_3a159de4_like', table_name='oeb_satfab')
    op.drop_index('oeb_satfab_satelite_1e0b139c', table_name='oeb_satfab')
    op.drop_index('oeb_satfab_satelite_1e0b139c_like', table_name='oeb_satfab')
    op.drop_table('oeb_satfab')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_table('vinculo')
    op.drop_index('oeb_funcgen_codigo_cc3656aa_like', table_name='oeb_funcgen')
    op.drop_table('oeb_funcgen')
    op.drop_table('cefetivo')
    op.drop_index('teste_vinculo_codigo_5ac4b12a_like', table_name='teste_vinculo')
    op.drop_table('teste_vinculo')
    op.drop_table('django_migrations')
    op.drop_table('unidade')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('colaborador')
    op.drop_table('instruc')
    op.drop_table('estcivil')
    op.drop_index('oeb_vcge_codigo_2bbf83d2_like', table_name='oeb_vcge')
    op.drop_table('oeb_vcge')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('transp_ramais')
    op.drop_index('teste_colaborador_Unidade_27a2ecdf', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_Unidade_27a2ecdf_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_ccomiss_49c8c674', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_ccomiss_49c8c674_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_cefetivo_5a41d609', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_cefetivo_5a41d609_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_codigo_28349944_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_estcivil_7239c9d5', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_estcivil_7239c9d5_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_instruc_c291fbab', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_instruc_c291fbab_like', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_vinculo_dbab0e16', table_name='teste_colaborador')
    op.drop_index('teste_colaborador_vinculo_dbab0e16_like', table_name='teste_colaborador')
    op.drop_table('teste_colaborador')
    op.drop_index('oeb_funcesp_codigo_8956b8b0_like', table_name='oeb_funcesp')
    op.drop_table('oeb_funcesp')
    op.drop_index('teste_instruc_codigo_ff3f83c2_like', table_name='teste_instruc')
    op.drop_table('teste_instruc')
    op.drop_index('oeb_orbita_sigla_d3e1ec37_like', table_name='oeb_orbita')
    op.drop_table('oeb_orbita')
    op.drop_index('teste_unidade_raiz_1acf81b7', table_name='teste_unidade')
    op.drop_index('teste_unidade_raiz_1acf81b7_like', table_name='teste_unidade')
    op.drop_index('teste_unidade_sigla_f4f45e80_like', table_name='teste_unidade')
    op.drop_index('teste_unidade_subordinacao_de841032', table_name='teste_unidade')
    op.drop_index('teste_unidade_subordinacao_de841032_like', table_name='teste_unidade')
    op.drop_table('teste_unidade')
    op.drop_table('distribccomiss')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_table('ccomiss')
    op.drop_index('teste_ccomiss_codigo_e39bd3e5_like', table_name='teste_ccomiss')
    op.drop_table('teste_ccomiss')
    op.drop_index('oeb_satfuncesp_codigo_46520026_like', table_name='oeb_satfuncesp')
    op.drop_index('oeb_satfuncesp_funcesp_d9c39550', table_name='oeb_satfuncesp')
    op.drop_index('oeb_satfuncesp_funcesp_d9c39550_like', table_name='oeb_satfuncesp')
    op.drop_index('oeb_satfuncesp_satelite_aafb9695', table_name='oeb_satfuncesp')
    op.drop_index('oeb_satfuncesp_satelite_aafb9695_like', table_name='oeb_satfuncesp')
    op.drop_table('oeb_satfuncesp')
    op.alter_column('cgp_ccomiss', 'nivel',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_index('cgp_ccomiss_codigo_318acd67_like', table_name='cgp_ccomiss')
    op.drop_index('cgp_cefetivo_codigo_be0d547c_like', table_name='cgp_cefetivo')
    op.add_column('cgp_colaborador', sa.Column('imagem_caminho', sa.String(), nullable=True))
    op.alter_column('cgp_colaborador', 'matricula',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('cgp_colaborador', 'genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('cgp_colaborador', 'nacionalidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('cgp_colaborador_Unidade_b0b0f355', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_Unidade_b0b0f355_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_ccomiss_82ae479d', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_ccomiss_82ae479d_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_cefetivo_f67210d3', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_cefetivo_f67210d3_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_codigo_bee3c83c_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_estcivil_dfbe4e2c', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_estcivil_dfbe4e2c_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_instruc_a1e1c268', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_instruc_a1e1c268_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_vinculo_1449d06e', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_vinculo_1449d06e_like', table_name='cgp_colaborador')
    op.drop_constraint('cgp_colaborador_ccomiss_82ae479d_fk_cgp_ccomiss_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_estcivil_dfbe4e2c_fk_cgp_estcivil_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_vinculo_1449d06e_fk_cgp_vinculo_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_Unidade_b0b0f355_fk_cgp_unidade_sigla', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_instruc_a1e1c268_fk_cgp_instruc_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_cefetivo_f67210d3_fk_cgp_cefetivo_codigo', 'cgp_colaborador', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_cefetivo', ['cefetivo'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_instruc', ['instruc'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_vinculo', ['vinculo'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_estcivil', ['estcivil'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_unidade', ['unidade'], ['sigla'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_ccomiss', ['ccomiss'], ['codigo'], ondelete='SET NULL')
    op.drop_column('cgp_colaborador', 'telefone')
    op.alter_column('cgp_distribccomiss', 'unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('cgp_distribccomiss_ccomiss_eb648a1c', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_ccomiss_eb648a1c_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_codigo_a6b3a715_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_substituto_b396caf3', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_substituto_b396caf3_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_titular_e6befee0', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_titular_e6befee0_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_unidade_9a2a74f0', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_unidade_9a2a74f0_like', table_name='cgp_distribccomiss')
    op.drop_constraint('cgp_distribccomiss_titular_e6befee0_fk_cgp_colaborador_codigo', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_substituto_b396caf3_fk_cgp_colab', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_ccomiss_eb648a1c_fk_cgp_ccomiss_codigo', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_unidade_9a2a74f0_fk_cgp_unidade_sigla', 'cgp_distribccomiss', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_colaborador', ['substituto'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_ccomiss', ['ccomiss'], ['codigo'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_colaborador', ['titular'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_unidade', ['unidade'], ['sigla'], ondelete='SET NULL')
    op.drop_index('cgp_estcivil_codigo_4b33928c_like', table_name='cgp_estcivil')
    op.drop_index('cgp_instruc_codigo_5eae7498_like', table_name='cgp_instruc')
    op.alter_column('cgp_unidade', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('cgp_unidade_raiz_dffb4eed', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_raiz_dffb4eed_like', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_sigla_63af7534_like', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_subordinacao_d8709bf6', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_subordinacao_d8709bf6_like', table_name='cgp_unidade')
    op.create_unique_constraint(None, 'cgp_unidade', ['nome'])
    op.drop_constraint('cgp_unidade_subordinacao_d8709bf6_fk_cgp_unidade_sigla', 'cgp_unidade', type_='foreignkey')
    op.drop_constraint('cgp_unidade_raiz_dffb4eed_fk_cgp_unidade_sigla', 'cgp_unidade', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_unidade', 'cgp_unidade', ['raiz'], ['sigla'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cgp_unidade', 'cgp_unidade', ['subordinacao'], ['sigla'], ondelete='CASCADE')
    op.drop_index('cgp_vinculo_codigo_be69ae0a_like', table_name='cgp_vinculo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('cgp_vinculo_codigo_be69ae0a_like', 'cgp_vinculo', ['codigo'], unique=False)
    op.drop_constraint(None, 'cgp_unidade', type_='foreignkey')
    op.drop_constraint(None, 'cgp_unidade', type_='foreignkey')
    op.create_foreign_key('cgp_unidade_raiz_dffb4eed_fk_cgp_unidade_sigla', 'cgp_unidade', 'cgp_unidade', ['raiz'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_unidade_subordinacao_d8709bf6_fk_cgp_unidade_sigla', 'cgp_unidade', 'cgp_unidade', ['subordinacao'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'cgp_unidade', type_='unique')
    op.create_index('cgp_unidade_subordinacao_d8709bf6_like', 'cgp_unidade', ['subordinacao'], unique=False)
    op.create_index('cgp_unidade_subordinacao_d8709bf6', 'cgp_unidade', ['subordinacao'], unique=False)
    op.create_index('cgp_unidade_sigla_63af7534_like', 'cgp_unidade', ['sigla'], unique=False)
    op.create_index('cgp_unidade_raiz_dffb4eed_like', 'cgp_unidade', ['raiz'], unique=False)
    op.create_index('cgp_unidade_raiz_dffb4eed', 'cgp_unidade', ['raiz'], unique=False)
    op.alter_column('cgp_unidade', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('cgp_instruc_codigo_5eae7498_like', 'cgp_instruc', ['codigo'], unique=False)
    op.create_index('cgp_estcivil_codigo_4b33928c_like', 'cgp_estcivil', ['codigo'], unique=False)
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.create_foreign_key('cgp_distribccomiss_unidade_9a2a74f0_fk_cgp_unidade_sigla', 'cgp_distribccomiss', 'cgp_unidade', ['unidade'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_ccomiss_eb648a1c_fk_cgp_ccomiss_codigo', 'cgp_distribccomiss', 'cgp_ccomiss', ['ccomiss'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_substituto_b396caf3_fk_cgp_colab', 'cgp_distribccomiss', 'cgp_colaborador', ['substituto'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_titular_e6befee0_fk_cgp_colaborador_codigo', 'cgp_distribccomiss', 'cgp_colaborador', ['titular'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_index('cgp_distribccomiss_unidade_9a2a74f0_like', 'cgp_distribccomiss', ['unidade'], unique=False)
    op.create_index('cgp_distribccomiss_unidade_9a2a74f0', 'cgp_distribccomiss', ['unidade'], unique=False)
    op.create_index('cgp_distribccomiss_titular_e6befee0_like', 'cgp_distribccomiss', ['titular'], unique=False)
    op.create_index('cgp_distribccomiss_titular_e6befee0', 'cgp_distribccomiss', ['titular'], unique=False)
    op.create_index('cgp_distribccomiss_substituto_b396caf3_like', 'cgp_distribccomiss', ['substituto'], unique=False)
    op.create_index('cgp_distribccomiss_substituto_b396caf3', 'cgp_distribccomiss', ['substituto'], unique=False)
    op.create_index('cgp_distribccomiss_codigo_a6b3a715_like', 'cgp_distribccomiss', ['codigo'], unique=False)
    op.create_index('cgp_distribccomiss_ccomiss_eb648a1c_like', 'cgp_distribccomiss', ['ccomiss'], unique=False)
    op.create_index('cgp_distribccomiss_ccomiss_eb648a1c', 'cgp_distribccomiss', ['ccomiss'], unique=False)
    op.alter_column('cgp_distribccomiss', 'unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('cgp_colaborador', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.create_foreign_key('cgp_colaborador_cefetivo_f67210d3_fk_cgp_cefetivo_codigo', 'cgp_colaborador', 'cgp_cefetivo', ['cefetivo'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_instruc_a1e1c268_fk_cgp_instruc_codigo', 'cgp_colaborador', 'cgp_instruc', ['instruc'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_Unidade_b0b0f355_fk_cgp_unidade_sigla', 'cgp_colaborador', 'cgp_unidade', ['unidade'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_vinculo_1449d06e_fk_cgp_vinculo_codigo', 'cgp_colaborador', 'cgp_vinculo', ['vinculo'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_estcivil_dfbe4e2c_fk_cgp_estcivil_codigo', 'cgp_colaborador', 'cgp_estcivil', ['estcivil'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_ccomiss_82ae479d_fk_cgp_ccomiss_codigo', 'cgp_colaborador', 'cgp_ccomiss', ['ccomiss'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_index('cgp_colaborador_vinculo_1449d06e_like', 'cgp_colaborador', ['vinculo'], unique=False)
    op.create_index('cgp_colaborador_vinculo_1449d06e', 'cgp_colaborador', ['vinculo'], unique=False)
    op.create_index('cgp_colaborador_instruc_a1e1c268_like', 'cgp_colaborador', ['instruc'], unique=False)
    op.create_index('cgp_colaborador_instruc_a1e1c268', 'cgp_colaborador', ['instruc'], unique=False)
    op.create_index('cgp_colaborador_estcivil_dfbe4e2c_like', 'cgp_colaborador', ['estcivil'], unique=False)
    op.create_index('cgp_colaborador_estcivil_dfbe4e2c', 'cgp_colaborador', ['estcivil'], unique=False)
    op.create_index('cgp_colaborador_codigo_bee3c83c_like', 'cgp_colaborador', ['codigo'], unique=False)
    op.create_index('cgp_colaborador_cefetivo_f67210d3_like', 'cgp_colaborador', ['cefetivo'], unique=False)
    op.create_index('cgp_colaborador_cefetivo_f67210d3', 'cgp_colaborador', ['cefetivo'], unique=False)
    op.create_index('cgp_colaborador_ccomiss_82ae479d_like', 'cgp_colaborador', ['ccomiss'], unique=False)
    op.create_index('cgp_colaborador_ccomiss_82ae479d', 'cgp_colaborador', ['ccomiss'], unique=False)
    op.create_index('cgp_colaborador_Unidade_b0b0f355_like', 'cgp_colaborador', ['unidade'], unique=False)
    op.create_index('cgp_colaborador_Unidade_b0b0f355', 'cgp_colaborador', ['unidade'], unique=False)
    op.alter_column('cgp_colaborador', 'nacionalidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cgp_colaborador', 'genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('cgp_colaborador', 'matricula',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_column('cgp_colaborador', 'imagem_caminho')
    op.create_index('cgp_cefetivo_codigo_be0d547c_like', 'cgp_cefetivo', ['codigo'], unique=False)
    op.create_index('cgp_ccomiss_codigo_318acd67_like', 'cgp_ccomiss', ['codigo'], unique=False)
    op.alter_column('cgp_ccomiss', 'nivel',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.create_table('oeb_satfuncesp',
    sa.Column('codigo', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('funcesp', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('satelite', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['funcesp'], ['oeb_funcesp.codigo'], name='oeb_satfuncesp_funcesp_d9c39550_fk_oeb_funcesp_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['satelite'], ['oeb_satelite.nssdc'], name='oeb_satfuncesp_satelite_aafb9695_fk_oeb_satelite_nssdc', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('codigo', name='oeb_satfuncesp_pkey')
    )
    op.create_index('oeb_satfuncesp_satelite_aafb9695_like', 'oeb_satfuncesp', ['satelite'], unique=False)
    op.create_index('oeb_satfuncesp_satelite_aafb9695', 'oeb_satfuncesp', ['satelite'], unique=False)
    op.create_index('oeb_satfuncesp_funcesp_d9c39550_like', 'oeb_satfuncesp', ['funcesp'], unique=False)
    op.create_index('oeb_satfuncesp_funcesp_d9c39550', 'oeb_satfuncesp', ['funcesp'], unique=False)
    op.create_index('oeb_satfuncesp_codigo_46520026_like', 'oeb_satfuncesp', ['codigo'], unique=False)
    op.create_table('teste_ccomiss',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('classe', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valorunitario', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='teste_ccomiss_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_ccomiss_codigo_e39bd3e5_like', 'teste_ccomiss', ['codigo'], unique=False)
    op.create_table('ccomiss',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('valorunitario', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='ccomiss_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('distribccomiss',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ccomiss', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('titular', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('substituto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nomef', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nomem', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargoc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ccomiss'], ['ccomiss.codigo'], name='distribccomiss_ccomiss_fkey'),
    sa.ForeignKeyConstraint(['substituto'], ['colaborador.codigo'], name='distribccomiss_substituto_fkey'),
    sa.ForeignKeyConstraint(['titular'], ['colaborador.codigo'], name='distribccomiss_titular_fkey'),
    sa.ForeignKeyConstraint(['unidade'], ['unidade.sigla'], name='distribccomiss_unidade_fkey'),
    sa.PrimaryKeyConstraint('codigo', name='distribccomiss_pkey')
    )
    op.create_table('teste_unidade',
    sa.Column('sigla', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('raiz', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subordinacao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sigla', name='teste_unidade_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_unidade_subordinacao_de841032_like', 'teste_unidade', ['subordinacao'], unique=False)
    op.create_index('teste_unidade_subordinacao_de841032', 'teste_unidade', ['subordinacao'], unique=False)
    op.create_index('teste_unidade_sigla_f4f45e80_like', 'teste_unidade', ['sigla'], unique=False)
    op.create_index('teste_unidade_raiz_1acf81b7_like', 'teste_unidade', ['raiz'], unique=False)
    op.create_index('teste_unidade_raiz_1acf81b7', 'teste_unidade', ['raiz'], unique=False)
    op.create_table('oeb_orbita',
    sa.Column('sigla', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sigla', name='oeb_orbita_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_orbita_sigla_d3e1ec37_like', 'oeb_orbita', ['sigla'], unique=False)
    op.create_table('teste_instruc',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='teste_instruc_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_instruc_codigo_ff3f83c2_like', 'teste_instruc', ['codigo'], unique=False)
    op.create_table('oeb_funcesp',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_funcesp_pkey')
    )
    op.create_index('oeb_funcesp_codigo_8956b8b0_like', 'oeb_funcesp', ['codigo'], unique=False)
    op.create_table('teste_colaborador',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('superior', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nacionalidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pne', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('admissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('demissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ramal', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('emailpessoal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('grauh', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ccomiss', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('cefetivo', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('estcivil', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('instruc', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('Unidade', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('vinculo', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Unidade'], ['teste_unidade.sigla'], name='teste_colaborador_Unidade_27a2ecdf_fk_teste_unidade_sigla', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['ccomiss'], ['teste_ccomiss.codigo'], name='teste_colaborador_ccomiss_49c8c674_fk_teste_ccomiss_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['cefetivo'], ['teste_cefetivo.codigo'], name='teste_colaborador_cefetivo_5a41d609_fk_teste_cefetivo_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['estcivil'], ['teste_estcivil.codigo'], name='teste_colaborador_estcivil_7239c9d5_fk_teste_estcivil_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['instruc'], ['teste_instruc.codigo'], name='teste_colaborador_instruc_c291fbab_fk_teste_instruc_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['vinculo'], ['teste_vinculo.codigo'], name='teste_colaborador_vinculo_dbab0e16_fk_teste_vinculo_codigo', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('codigo', name='teste_colaborador_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_colaborador_vinculo_dbab0e16_like', 'teste_colaborador', ['vinculo'], unique=False)
    op.create_index('teste_colaborador_vinculo_dbab0e16', 'teste_colaborador', ['vinculo'], unique=False)
    op.create_index('teste_colaborador_instruc_c291fbab_like', 'teste_colaborador', ['instruc'], unique=False)
    op.create_index('teste_colaborador_instruc_c291fbab', 'teste_colaborador', ['instruc'], unique=False)
    op.create_index('teste_colaborador_estcivil_7239c9d5_like', 'teste_colaborador', ['estcivil'], unique=False)
    op.create_index('teste_colaborador_estcivil_7239c9d5', 'teste_colaborador', ['estcivil'], unique=False)
    op.create_index('teste_colaborador_codigo_28349944_like', 'teste_colaborador', ['codigo'], unique=False)
    op.create_index('teste_colaborador_cefetivo_5a41d609_like', 'teste_colaborador', ['cefetivo'], unique=False)
    op.create_index('teste_colaborador_cefetivo_5a41d609', 'teste_colaborador', ['cefetivo'], unique=False)
    op.create_index('teste_colaborador_ccomiss_49c8c674_like', 'teste_colaborador', ['ccomiss'], unique=False)
    op.create_index('teste_colaborador_ccomiss_49c8c674', 'teste_colaborador', ['ccomiss'], unique=False)
    op.create_index('teste_colaborador_Unidade_27a2ecdf_like', 'teste_colaborador', ['Unidade'], unique=False)
    op.create_index('teste_colaborador_Unidade_27a2ecdf', 'teste_colaborador', ['Unidade'], unique=False)
    op.create_table('transp_ramais',
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lotacao', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=150), autoincrement=False, nullable=True)
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('oeb_vcge',
    sa.Column('codigo', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('termo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_vcge_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_vcge_codigo_2bbf83d2_like', 'oeb_vcge', ['codigo'], unique=False)
    op.create_table('estcivil',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='estcivil_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('instruc',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='instruc_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('colaborador',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('matricula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('superior', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nascimento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nacionalidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pne', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('demissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ramal', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('emailpessoal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grauh', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vinculo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cefetivo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ccomiss', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estcivil', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instruc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ccomiss'], ['ccomiss.codigo'], name='colaborador_ccomiss_fkey'),
    sa.ForeignKeyConstraint(['cefetivo'], ['cefetivo.codigo'], name='colaborador_cefetivo_fkey'),
    sa.ForeignKeyConstraint(['estcivil'], ['estcivil.codigo'], name='colaborador_estcivil_fkey'),
    sa.ForeignKeyConstraint(['instruc'], ['instruc.codigo'], name='colaborador_instruc_fkey'),
    sa.ForeignKeyConstraint(['unidade'], ['unidade.sigla'], name='colaborador_unidade_fkey'),
    sa.ForeignKeyConstraint(['vinculo'], ['vinculo.codigo'], name='colaborador_vinculo_fkey'),
    sa.PrimaryKeyConstraint('codigo', name='colaborador_pkey')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('unidade',
    sa.Column('sigla', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subordinacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raiz', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['raiz'], ['unidade.sigla'], name='unidade_raiz_fkey'),
    sa.ForeignKeyConstraint(['subordinacao'], ['unidade.sigla'], name='unidade_subordinacao_fkey'),
    sa.PrimaryKeyConstraint('sigla', name='unidade_pkey'),
    sa.UniqueConstraint('nome', name='unidade_nome_key')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('teste_vinculo',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='teste_vinculo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_vinculo_codigo_5ac4b12a_like', 'teste_vinculo', ['codigo'], unique=False)
    op.create_table('cefetivo',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('regime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo', name='cefetivo_pkey')
    )
    op.create_table('oeb_funcgen',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_funcgen_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_funcgen_codigo_cc3656aa_like', 'oeb_funcgen', ['codigo'], unique=False)
    op.create_table('vinculo',
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='vinculo_pkey')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_group_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('oeb_satfab',
    sa.Column('codigo', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('entidade', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('satelite', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entidade'], ['oeb_entidade.codigo'], name='oeb_satfab_entidade_3a159de4_fk_oeb_entidade_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['satelite'], ['oeb_satelite.nssdc'], name='oeb_satfab_satelite_1e0b139c_fk_oeb_satelite_nssdc', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('codigo', name='oeb_satfab_pkey')
    )
    op.create_index('oeb_satfab_satelite_1e0b139c_like', 'oeb_satfab', ['satelite'], unique=False)
    op.create_index('oeb_satfab_satelite_1e0b139c', 'oeb_satfab', ['satelite'], unique=False)
    op.create_index('oeb_satfab_entidade_3a159de4_like', 'oeb_satfab', ['entidade'], unique=False)
    op.create_index('oeb_satfab_entidade_3a159de4', 'oeb_satfab', ['entidade'], unique=False)
    op.create_index('oeb_satfab_codigo_c16b5828_like', 'oeb_satfab', ['codigo'], unique=False)
    op.create_table('teste_estcivil',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='teste_estcivil_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_estcivil_codigo_b590c4c6_like', 'teste_estcivil', ['codigo'], unique=False)
    op.create_table('oeb_status',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_status_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_status_codigo_c473e20b_like', 'oeb_status', ['codigo'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('oeb_veiculo',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_veiculo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_veiculo_codigo_d02fbc65_like', 'oeb_veiculo', ['codigo'], unique=False)
    op.create_table('oeb_satpropri',
    sa.Column('codigo', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('entidade', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('satelite', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entidade'], ['oeb_entidade.codigo'], name='oeb_satpropri_entidade_2c531a8e_fk_oeb_entidade_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['satelite'], ['oeb_satelite.nssdc'], name='oeb_satpropri_satelite_9ac3b440_fk_oeb_satelite_nssdc', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('codigo', name='oeb_satpropri_pkey')
    )
    op.create_index('oeb_satpropri_satelite_9ac3b440_like', 'oeb_satpropri', ['satelite'], unique=False)
    op.create_index('oeb_satpropri_satelite_9ac3b440', 'oeb_satpropri', ['satelite'], unique=False)
    op.create_index('oeb_satpropri_entidade_2c531a8e_like', 'oeb_satpropri', ['entidade'], unique=False)
    op.create_index('oeb_satpropri_entidade_2c531a8e', 'oeb_satpropri', ['entidade'], unique=False)
    op.create_index('oeb_satpropri_codigo_10cd50e3_like', 'oeb_satpropri', ['codigo'], unique=False)
    op.create_table('teste_cefetivo',
    sa.Column('codigo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('regime', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo', name='teste_cefetivo_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('teste_cefetivo_codigo_c691b85c_like', 'teste_cefetivo', ['codigo'], unique=False)
    op.create_table('oeb_base',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_base_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_base_codigo_b1ebede0_like', 'oeb_base', ['codigo'], unique=False)
    op.create_table('oeb_entidade',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codigo', name='oeb_entidade_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('oeb_entidade_codigo_7595804c_like', 'oeb_entidade', ['codigo'], unique=False)
    op.create_table('teste_distribccomiss',
    sa.Column('codigo', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('nomef', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nomem', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cargoc', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ccomiss', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('substituto', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('titular', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ccomiss'], ['teste_ccomiss.codigo'], name='teste_distribccomiss_ccomiss_fcb54ec6_fk_teste_ccomiss_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['substituto'], ['teste_colaborador.codigo'], name='teste_distribccomiss_substituto_110b6333_fk_teste_col', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['titular'], ['teste_colaborador.codigo'], name='teste_distribccomiss_titular_4a41cc55_fk_teste_col', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['unidade'], ['teste_unidade.sigla'], name='teste_distribccomiss_unidade_2a16a533_fk_teste_unidade_sigla', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('codigo', name='teste_distribccomiss_pkey')
    )
    op.create_index('teste_distribccomiss_unidade_2a16a533_like', 'teste_distribccomiss', ['unidade'], unique=False)
    op.create_index('teste_distribccomiss_unidade_2a16a533', 'teste_distribccomiss', ['unidade'], unique=False)
    op.create_index('teste_distribccomiss_titular_4a41cc55_like', 'teste_distribccomiss', ['titular'], unique=False)
    op.create_index('teste_distribccomiss_titular_4a41cc55', 'teste_distribccomiss', ['titular'], unique=False)
    op.create_index('teste_distribccomiss_substituto_110b6333_like', 'teste_distribccomiss', ['substituto'], unique=False)
    op.create_index('teste_distribccomiss_substituto_110b6333', 'teste_distribccomiss', ['substituto'], unique=False)
    op.create_index('teste_distribccomiss_codigo_59e1c1dc_like', 'teste_distribccomiss', ['codigo'], unique=False)
    op.create_index('teste_distribccomiss_ccomiss_fcb54ec6_like', 'teste_distribccomiss', ['ccomiss'], unique=False)
    op.create_index('teste_distribccomiss_ccomiss_fcb54ec6', 'teste_distribccomiss', ['ccomiss'], unique=False)
    op.create_table('oeb_satelite',
    sa.Column('nssdc', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('massainicial', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('lancamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fimop', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('base', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('entidade', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('funcgen', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('orbita', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('vcge', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('veiculo', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['base'], ['oeb_base.codigo'], name='oeb_satelite_base_07a404b9_fk_oeb_base_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['entidade'], ['oeb_entidade.codigo'], name='oeb_satelite_entidade_a25587bd_fk_oeb_entidade_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['funcgen'], ['oeb_funcgen.codigo'], name='oeb_satelite_funcgen_b8d6b7a6_fk_oeb_funcgen_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['orbita'], ['oeb_orbita.sigla'], name='oeb_satelite_orbita_d15b2592_fk_oeb_orbita_sigla', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['status'], ['oeb_status.codigo'], name='oeb_satelite_status_528c4e00_fk_oeb_status_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['vcge'], ['oeb_vcge.codigo'], name='oeb_satelite_vcge_a741bfd4_fk_oeb_vcge_codigo', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['veiculo'], ['oeb_veiculo.codigo'], name='oeb_satelite_veiculo_10f6c700_fk_oeb_veiculo_codigo', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('nssdc', name='oeb_satelite_pkey')
    )
    op.create_index('oeb_satelite_veiculo_10f6c700_like', 'oeb_satelite', ['veiculo'], unique=False)
    op.create_index('oeb_satelite_veiculo_10f6c700', 'oeb_satelite', ['veiculo'], unique=False)
    op.create_index('oeb_satelite_vcge_a741bfd4_like', 'oeb_satelite', ['vcge'], unique=False)
    op.create_index('oeb_satelite_vcge_a741bfd4', 'oeb_satelite', ['vcge'], unique=False)
    op.create_index('oeb_satelite_status_528c4e00_like', 'oeb_satelite', ['status'], unique=False)
    op.create_index('oeb_satelite_status_528c4e00', 'oeb_satelite', ['status'], unique=False)
    op.create_index('oeb_satelite_orbita_d15b2592_like', 'oeb_satelite', ['orbita'], unique=False)
    op.create_index('oeb_satelite_orbita_d15b2592', 'oeb_satelite', ['orbita'], unique=False)
    op.create_index('oeb_satelite_nssdc_3c8b1650_like', 'oeb_satelite', ['nssdc'], unique=False)
    op.create_index('oeb_satelite_funcgen_b8d6b7a6_like', 'oeb_satelite', ['funcgen'], unique=False)
    op.create_index('oeb_satelite_funcgen_b8d6b7a6', 'oeb_satelite', ['funcgen'], unique=False)
    op.create_index('oeb_satelite_entidade_a25587bd_like', 'oeb_satelite', ['entidade'], unique=False)
    op.create_index('oeb_satelite_entidade_a25587bd', 'oeb_satelite', ['entidade'], unique=False)
    op.create_index('oeb_satelite_base_07a404b9_like', 'oeb_satelite', ['base'], unique=False)
    op.create_index('oeb_satelite_base_07a404b9', 'oeb_satelite', ['base'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq')
    )
    # ### end Alembic commands ###
