"""IDs

Revision ID: 4ed97a896b6d
Revises: 9a3856eb7357
Create Date: 2022-05-24 08:46:55.130678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed97a896b6d'
down_revision = '9a3856eb7357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cgp_colaborador', sa.Column('id_solides', sa.String(), nullable=True))
    op.add_column('cgp_colaborador', sa.Column('id_ad', sa.String(), nullable=True))
    op.add_column('cgp_colaborador', sa.Column('id_avaya', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cgp_colaborador', 'id_avaya')
    op.drop_column('cgp_colaborador', 'id_ad')
    op.drop_column('cgp_colaborador', 'id_solides')
    # ### end Alembic commands ###
