"""empty message

Revision ID: 567772495e6b
Revises: d8bcb2449b81
Create Date: 2022-04-18 10:46:02.844172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567772495e6b'
down_revision = 'd8bcb2449b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cgp_colaborador', sa.Column('solides_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cgp_colaborador', 'solides_id')
    # ### end Alembic commands ###
