"""Relacionamentos

Revision ID: 6912586bee5e
Revises: 016edb5d511f
Create Date: 2022-05-23 12:37:50.099578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6912586bee5e'
down_revision = '016edb5d511f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacionamento', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('relacionamento', 'id_solides',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('relacionamento_id_solides_fkey', 'relacionamento', type_='foreignkey')
    op.drop_constraint('relacionamento_id_avaya_fkey', 'relacionamento', type_='foreignkey')
    op.drop_constraint('relacionamento_colaborador_fkey', 'relacionamento', type_='foreignkey')
    op.drop_constraint('relacionamento_id_ad_fkey', 'relacionamento', type_='foreignkey')
    op.drop_column('relacionamento', 'colaborador')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacionamento', sa.Column('colaborador', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('relacionamento_id_ad_fkey', 'relacionamento', 'cgp_unidade', ['id_ad'], ['sigla'], ondelete='SET NULL')
    op.create_foreign_key('relacionamento_colaborador_fkey', 'relacionamento', 'cgp_colaborador', ['colaborador'], ['codigo'], ondelete='CASCADE')
    op.create_foreign_key('relacionamento_id_avaya_fkey', 'relacionamento', 'cgp_colaborador', ['id_avaya'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key('relacionamento_id_solides_fkey', 'relacionamento', 'cgp_ccomiss', ['id_solides'], ['codigo'], ondelete='CASCADE')
    op.alter_column('relacionamento', 'id_solides',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('relacionamento', 'email')
    # ### end Alembic commands ###
