"""Ativo

Revision ID: 74964cf87b89
Revises: b5aa64fc148b
Create Date: 2022-05-24 08:42:59.091867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74964cf87b89'
down_revision = 'b5aa64fc148b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cgp_colaborador', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cgp_colaborador', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
