"""Ativo

Revision ID: 9a3856eb7357
Revises: f593f0ca0c55
Create Date: 2022-05-24 08:44:00.260512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3856eb7357'
down_revision = 'f593f0ca0c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cgp_colaborador', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cgp_colaborador', 'active')
    # ### end Alembic commands ###
