"""CPF e imagem

Revision ID: b5aa64fc148b
Revises: 6912586bee5e
Create Date: 2022-05-24 08:10:03.421128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5aa64fc148b'
down_revision = '6912586bee5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cgp_colaborador', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('cgp_colaborador', 'solides_id')
    op.drop_column('cgp_colaborador', 'imagem_caminho')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cgp_colaborador', sa.Column('imagem_caminho', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cgp_colaborador', sa.Column('solides_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('cgp_colaborador', 'image')
    # ### end Alembic commands ###
