"""empty message

Revision ID: c504eee28f05
Revises: 4da22c815978
Create Date: 2022-04-14 09:47:11.303982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c504eee28f05'
down_revision = '4da22c815978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cgp_ccomiss_codigo_318acd67_like', table_name='cgp_ccomiss')
    op.drop_index('cgp_cefetivo_codigo_be0d547c_like', table_name='cgp_cefetivo')
    op.add_column('cgp_colaborador', sa.Column('imagem_caminho', sa.String(), nullable=True))
    op.alter_column('cgp_colaborador', 'genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('cgp_colaborador', 'nacionalidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('cgp_colaborador_Unidade_b0b0f355', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_Unidade_b0b0f355_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_ccomiss_82ae479d', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_ccomiss_82ae479d_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_cefetivo_f67210d3', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_cefetivo_f67210d3_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_codigo_bee3c83c_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_estcivil_dfbe4e2c', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_estcivil_dfbe4e2c_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_instruc_a1e1c268', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_instruc_a1e1c268_like', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_vinculo_1449d06e', table_name='cgp_colaborador')
    op.drop_index('cgp_colaborador_vinculo_1449d06e_like', table_name='cgp_colaborador')
    op.drop_constraint('cgp_colaborador_estcivil_dfbe4e2c_fk_cgp_estcivil_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_ccomiss_82ae479d_fk_cgp_ccomiss_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_cefetivo_f67210d3_fk_cgp_cefetivo_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_Unidade_b0b0f355_fk_cgp_unidade_sigla', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_instruc_a1e1c268_fk_cgp_instruc_codigo', 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint('cgp_colaborador_vinculo_1449d06e_fk_cgp_vinculo_codigo', 'cgp_colaborador', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_ccomiss', ['ccomiss'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_instruc', ['instruc'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_vinculo', ['vinculo'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_unidade', ['unidade'], ['sigla'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_cefetivo', ['cefetivo'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_colaborador', 'cgp_estcivil', ['estcivil'], ['codigo'], ondelete='SET NULL')
    op.drop_column('cgp_colaborador', 'telefone')
    op.alter_column('cgp_distribccomiss', 'unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('cgp_distribccomiss_ccomiss_eb648a1c', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_ccomiss_eb648a1c_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_codigo_a6b3a715_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_substituto_b396caf3', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_substituto_b396caf3_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_titular_e6befee0', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_titular_e6befee0_like', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_unidade_9a2a74f0', table_name='cgp_distribccomiss')
    op.drop_index('cgp_distribccomiss_unidade_9a2a74f0_like', table_name='cgp_distribccomiss')
    op.drop_constraint('cgp_distribccomiss_unidade_9a2a74f0_fk_cgp_unidade_sigla', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_substituto_b396caf3_fk_cgp_colab', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_titular_e6befee0_fk_cgp_colaborador_codigo', 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint('cgp_distribccomiss_ccomiss_eb648a1c_fk_cgp_ccomiss_codigo', 'cgp_distribccomiss', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_colaborador', ['titular'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_ccomiss', ['ccomiss'], ['codigo'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_colaborador', ['substituto'], ['codigo'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cgp_distribccomiss', 'cgp_unidade', ['unidade'], ['sigla'], ondelete='SET NULL')
    op.drop_index('cgp_estcivil_codigo_4b33928c_like', table_name='cgp_estcivil')
    op.drop_index('cgp_instruc_codigo_5eae7498_like', table_name='cgp_instruc')
    op.alter_column('cgp_unidade', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('cgp_unidade_raiz_dffb4eed', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_raiz_dffb4eed_like', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_sigla_63af7534_like', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_subordinacao_d8709bf6', table_name='cgp_unidade')
    op.drop_index('cgp_unidade_subordinacao_d8709bf6_like', table_name='cgp_unidade')
    op.create_unique_constraint(None, 'cgp_unidade', ['nome'])
    op.drop_constraint('cgp_unidade_subordinacao_d8709bf6_fk_cgp_unidade_sigla', 'cgp_unidade', type_='foreignkey')
    op.drop_constraint('cgp_unidade_raiz_dffb4eed_fk_cgp_unidade_sigla', 'cgp_unidade', type_='foreignkey')
    op.create_foreign_key(None, 'cgp_unidade', 'cgp_unidade', ['subordinacao'], ['sigla'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cgp_unidade', 'cgp_unidade', ['raiz'], ['sigla'], ondelete='CASCADE')
    op.drop_index('cgp_vinculo_codigo_be69ae0a_like', table_name='cgp_vinculo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('cgp_vinculo_codigo_be69ae0a_like', 'cgp_vinculo', ['codigo'], unique=False)
    op.drop_constraint(None, 'cgp_unidade', type_='foreignkey')
    op.drop_constraint(None, 'cgp_unidade', type_='foreignkey')
    op.create_foreign_key('cgp_unidade_raiz_dffb4eed_fk_cgp_unidade_sigla', 'cgp_unidade', 'cgp_unidade', ['raiz'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_unidade_subordinacao_d8709bf6_fk_cgp_unidade_sigla', 'cgp_unidade', 'cgp_unidade', ['subordinacao'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'cgp_unidade', type_='unique')
    op.create_index('cgp_unidade_subordinacao_d8709bf6_like', 'cgp_unidade', ['subordinacao'], unique=False)
    op.create_index('cgp_unidade_subordinacao_d8709bf6', 'cgp_unidade', ['subordinacao'], unique=False)
    op.create_index('cgp_unidade_sigla_63af7534_like', 'cgp_unidade', ['sigla'], unique=False)
    op.create_index('cgp_unidade_raiz_dffb4eed_like', 'cgp_unidade', ['raiz'], unique=False)
    op.create_index('cgp_unidade_raiz_dffb4eed', 'cgp_unidade', ['raiz'], unique=False)
    op.alter_column('cgp_unidade', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index('cgp_instruc_codigo_5eae7498_like', 'cgp_instruc', ['codigo'], unique=False)
    op.create_index('cgp_estcivil_codigo_4b33928c_like', 'cgp_estcivil', ['codigo'], unique=False)
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.drop_constraint(None, 'cgp_distribccomiss', type_='foreignkey')
    op.create_foreign_key('cgp_distribccomiss_ccomiss_eb648a1c_fk_cgp_ccomiss_codigo', 'cgp_distribccomiss', 'cgp_ccomiss', ['ccomiss'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_titular_e6befee0_fk_cgp_colaborador_codigo', 'cgp_distribccomiss', 'cgp_colaborador', ['titular'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_substituto_b396caf3_fk_cgp_colab', 'cgp_distribccomiss', 'cgp_colaborador', ['substituto'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_distribccomiss_unidade_9a2a74f0_fk_cgp_unidade_sigla', 'cgp_distribccomiss', 'cgp_unidade', ['unidade'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_index('cgp_distribccomiss_unidade_9a2a74f0_like', 'cgp_distribccomiss', ['unidade'], unique=False)
    op.create_index('cgp_distribccomiss_unidade_9a2a74f0', 'cgp_distribccomiss', ['unidade'], unique=False)
    op.create_index('cgp_distribccomiss_titular_e6befee0_like', 'cgp_distribccomiss', ['titular'], unique=False)
    op.create_index('cgp_distribccomiss_titular_e6befee0', 'cgp_distribccomiss', ['titular'], unique=False)
    op.create_index('cgp_distribccomiss_substituto_b396caf3_like', 'cgp_distribccomiss', ['substituto'], unique=False)
    op.create_index('cgp_distribccomiss_substituto_b396caf3', 'cgp_distribccomiss', ['substituto'], unique=False)
    op.create_index('cgp_distribccomiss_codigo_a6b3a715_like', 'cgp_distribccomiss', ['codigo'], unique=False)
    op.create_index('cgp_distribccomiss_ccomiss_eb648a1c_like', 'cgp_distribccomiss', ['ccomiss'], unique=False)
    op.create_index('cgp_distribccomiss_ccomiss_eb648a1c', 'cgp_distribccomiss', ['ccomiss'], unique=False)
    op.alter_column('cgp_distribccomiss', 'unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('cgp_colaborador', sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.drop_constraint(None, 'cgp_colaborador', type_='foreignkey')
    op.create_foreign_key('cgp_colaborador_vinculo_1449d06e_fk_cgp_vinculo_codigo', 'cgp_colaborador', 'cgp_vinculo', ['vinculo'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_instruc_a1e1c268_fk_cgp_instruc_codigo', 'cgp_colaborador', 'cgp_instruc', ['instruc'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_Unidade_b0b0f355_fk_cgp_unidade_sigla', 'cgp_colaborador', 'cgp_unidade', ['unidade'], ['sigla'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_cefetivo_f67210d3_fk_cgp_cefetivo_codigo', 'cgp_colaborador', 'cgp_cefetivo', ['cefetivo'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_ccomiss_82ae479d_fk_cgp_ccomiss_codigo', 'cgp_colaborador', 'cgp_ccomiss', ['ccomiss'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('cgp_colaborador_estcivil_dfbe4e2c_fk_cgp_estcivil_codigo', 'cgp_colaborador', 'cgp_estcivil', ['estcivil'], ['codigo'], initially='DEFERRED', deferrable=True)
    op.create_index('cgp_colaborador_vinculo_1449d06e_like', 'cgp_colaborador', ['vinculo'], unique=False)
    op.create_index('cgp_colaborador_vinculo_1449d06e', 'cgp_colaborador', ['vinculo'], unique=False)
    op.create_index('cgp_colaborador_instruc_a1e1c268_like', 'cgp_colaborador', ['instruc'], unique=False)
    op.create_index('cgp_colaborador_instruc_a1e1c268', 'cgp_colaborador', ['instruc'], unique=False)
    op.create_index('cgp_colaborador_estcivil_dfbe4e2c_like', 'cgp_colaborador', ['estcivil'], unique=False)
    op.create_index('cgp_colaborador_estcivil_dfbe4e2c', 'cgp_colaborador', ['estcivil'], unique=False)
    op.create_index('cgp_colaborador_codigo_bee3c83c_like', 'cgp_colaborador', ['codigo'], unique=False)
    op.create_index('cgp_colaborador_cefetivo_f67210d3_like', 'cgp_colaborador', ['cefetivo'], unique=False)
    op.create_index('cgp_colaborador_cefetivo_f67210d3', 'cgp_colaborador', ['cefetivo'], unique=False)
    op.create_index('cgp_colaborador_ccomiss_82ae479d_like', 'cgp_colaborador', ['ccomiss'], unique=False)
    op.create_index('cgp_colaborador_ccomiss_82ae479d', 'cgp_colaborador', ['ccomiss'], unique=False)
    op.create_index('cgp_colaborador_Unidade_b0b0f355_like', 'cgp_colaborador', ['unidade'], unique=False)
    op.create_index('cgp_colaborador_Unidade_b0b0f355', 'cgp_colaborador', ['unidade'], unique=False)
    op.alter_column('cgp_colaborador', 'nacionalidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cgp_colaborador', 'genero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('cgp_colaborador', 'imagem_caminho')
    op.create_index('cgp_cefetivo_codigo_be0d547c_like', 'cgp_cefetivo', ['codigo'], unique=False)
    op.create_index('cgp_ccomiss_codigo_318acd67_like', 'cgp_ccomiss', ['codigo'], unique=False)
    # ### end Alembic commands ###
